### ISSUE TITLE
arma2oaserver.exe keeps crashing when hiveEXT.dll initializes

### ISSUE THREAD

**Issue by infeex** [rajkosto/hive#1]
as the title says, my arma2oaserver.exe keeps crashing when hiveEXT.dll is initializing.

I mainly run the blisshive and it works like a charm.

heres a small output of my .rpt file:

Mods: @hive
Distribution: 0
Version 1.62.96585
Fault address:  6EEC8F70 00:6EEC8F70 Unknown module
file:     dayz_1 (__cur_mp)
world:    chernarus

Registers:
EAX:77613665 EBX:1D63BE14
ECX:00000000 EDX:6EEC8F70
ESI:00000000 EDI:00000000
CS:EIP:0023:6EEC8F70
SS:ESP:002B:1E00FAF4  EBP:1E00FAFC
DS:002B  ES:002B  FS:0053  GS:002B
# Flags:00010246

note: Minidump has been generated into the file Bliss\arma2oaserver.mdmp
 0:32:51 UH1Wreck_DZ: MainTurret - unknown animation source MainTurret
 0:32:51 UH1Wreck_DZ: MainGun - unknown animation source mainGun
 0:32:51 UH1Wreck_DZ: Gatling - unknown animation source Gatling
 0:32:52 "CLEANUP: INITIALIZING CLEANUP SCRIPT"

**Comment by rajkosto** [comment]
Do you have http://www.microsoft.com/en-us/download/details.aspx?id=8328 installed ?
Have you followed the README, like, is there Database.dll, tbb.dll and tbbmalloc.dll in the root arma2 dir, while there's HiveExt.dll in @hive, and a properly configured HiveExt.ini in your server's config dir ?

**Comment by infeex** [comment]
Yes there is the c++ thing installed you posted and everythings on its place where it needs to be.

**Comment by rajkosto** [comment]
Are you trying to run it with the bliss database structure ?

**Comment by infeex** [comment]
Nope. I'm using the SQL structure provided with ur package.
Is there any other way i can contact you? Don't like to spam here... :P

**Comment by rajkosto** [comment]
There's an email in the README file. Send the mdmp file there too
