### ISSUE TITLE
Feature Request: Set year/month/date in hiveext.ini

### ISSUE THREAD

**Issue by Stapo** [rajkosto/hive#4]
Like This:

;Possible values: Local, Static
Type = Static
;If using Static type, the year/month/day to set the date to
Year = 2012
Month = 7
Day = 3

So then people can make it so its a full moon every night.

**Comment by rajkosto** [comment]
Done in https://github.com/rajkosto/hive/commit/7373bbe7e5d2b9ecdeb97704453c7e2d47e57de8
Better configuration format though, read updated sample HiveExt.ini for details
