### ISSUE TITLE
Compile errors

### ISSUE THREAD

**Issue by Muppet1856** [rajkosto/hive#6]
When I go to compile, I get these two errors to start with...

Error   2   error LNK1104: cannot open file 'libboost_filesystem-vc100-mt-gd-1_52.lib'  C:\Users\xxx\Documents\Visual Studio 2010\Projects\hive-master\Hive\Source\Restarter\LINK   Restarter

Error   1   error MSB3073: The command "bash C:\Users\xxx\Documents\Visual Studio 2010\Projects\hive-master\Hive\Source\HiveLib\version_gen.sh C:\Users\xxx\Documents\Visual Studio 2010\Projects\hive-master\Hive\Source\HiveLib\Version.cpp.template C:\Users\xxx\Documents\Visual Studio 2010\Projects\hive-master\Hive\Source\HiveLib\Version.cpp
:VCEnd" exited with code 9009.  C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\Microsoft.CppCommon.targets   103 6   HiveLib

**Comment by rajkosto** [comment]
1. boost is a required dependency, read the readme
2. install gitextensions and let it pollute your path completely (the red option)
   this also requires that the folder you're compiling from be in a valid git repository

**Comment by Muppet1856** [comment]
Error   90  error LNK1104: cannot open file 'libboost_filesystem-vc100-mt-1_52.lib' C:\Users\zellenj\Documents\Visual Studio 2010\Projects\hive-master\Hive\Source\Restarter\LINK   Restarter

I compiled boost, per the boost instructions.  But I don't see any libboost.....

Oh, and now I get 
Error   1   error MSB3073: The command "bash C:\Users\zellenj\Documents\Visual Studio 2010\Projects\hive-master\Hive\Source\HiveLib\version_gen.sh C:\Users\zellenj\Documents\Visual Studio 2010\Projects\hive-master\Hive\Source\HiveLib\Version.cpp.template C:\Users\zellenj\Documents\Visual Studio 2010\Projects\hive-master\Hive\Source\HiveLib\Version.cpp
:VCEnd" exited with code 127.   C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\Microsoft.CppCommon.targets   103 6   HiveLib

**Comment by Muppet1856** [comment]
Check that - it compiled under vc110 - I need to force vc100...

**Comment by rajkosto** [comment]
Shouldn't have upgraded the projects to vs2012 ( go switch back the platform toolchain on all of them back to v100)
And also, compiling boost definitely gave you some .lib files
Just add them to visual studio directories library paths

**Comment by Muppet1856** [comment]
Recompiled to VC100 - installed gitextensions
Now I get:

Error   1   error MSB3073: The command "bash C:\Users\xxx\Documents\Visual Studio 2010\Projects\hive-master\Hive\Source\HiveLib\version_gen.sh C:\Users\xxx\Documents\Visual Studio 2010\Projects\hive-master\Hive\Source\HiveLib\Version.cpp.template C:\Users\xxx\Documents\Visual Studio 2010\Projects\hive-master\Hive\Source\HiveLib\Version.cpp
:VCEnd" exited with code 127.   C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\Microsoft.CppCommon.targets   103 6   HiveLib

**Comment by rajkosto** [comment]
Do bash and git work from a spawned command prompt ? If so, just restart visual studio
Alternatively, you can just remove the build step that generates version.cpp, it's not important, it only integrates the git commit hash into the exe so i always know what commit it came from

**Comment by Muppet1856** [comment]
Of course, the command line was too long...  Wow.  Too many nested folders.  CLOSED  THANK YOU!!!
