### ISSUE TITLE
Setup the Visual Environment

### ISSUE THREAD

**Issue by harmdhast** [rajkosto/hive#9]
Hello,
I keep having lots of issues with the dependencies and all that stuff. I've done all that you said in the Readme but I keep having Errors, Can you help me with this ?

Thanks Dude
Harmdhast

Sorry for my bad english, i'm a french guy.

**Comment by rajkosto** [comment]
'Errors' is a great description of any problem.

**Comment by harmdhast** [comment]
Le 12/10/2013 13:55, Rajko Stojadinovic a écrit :

> 'Errors' is a great description of any problem.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/rajkosto/hive/issues/9#issuecomment-26196131.
> 
> Ow sorry, It's just that Visual Studio is new for me... I learn C++ with 
> Code Blocks and i'm now totally lost.
> I've errors like : Can't find includes, ToolsVersion=12 is not found , 
> using version 4...
> Can you help me with Skype or TeamViewer ?

Thanks for your help,
harmdhast

**Comment by rajkosto** [comment]
You're not going to be able to accomplish anything unless you are experienced enough to at least compile all the dependenices (which I've made pretty easy by making a repo for each one with standardised vcxproj files, and mentioning all the steps in the README here)
As for the ToolsVersion thing, use the Visual Studio that was mentioned in the README, or newer, like 2013.

**Comment by harmdhast** [comment]
Okay i didn't tell you the thruth, i just want to make a server with my friends and learnt a bit C++ but with CodeBlock (I already dev in Java and WinDev) . I just want to make the hive Postgre compatible cause the current hivedll make the server crashes.
Sorry for wasting your time,
Harmdhast
